parent_cfg: configs/exps/pretrain/enerf/dtu_pretrain.yaml
exp_name: enerf_ours

require_view_selection: True

# module
network_module: lib.networks.boost_enerf.network

# task config
enerf:
    train_input_views: [5, 6, 7]
    cost_volume_input_views: 3
    test_input_views: 6
    cas_config:
        k_best: 4

train:
    batch_size: 1
    sampler_meta:
        input_views_num: [5, 6, 7] 
        input_views_prob: [0.1, 0.8, 0.1]

test:
    batch_size: 1
    sampler_meta:
        input_views_num: [6]
