parent_cfg: configs/exps/evaluate/enerf_ours/base_eval.yaml

dataset_module: lib.datasets.free.enerf_base

train_dataset:
    data_root: 'free_dataset' #
    split: 'train'
    input_h_w: [480, 736]
    batch_size: 1
    input_ratio: 1.

test_dataset:
    data_root: 'free_dataset' #
    split: 'test'
    input_h_w: [480, 736]
    batch_size: 1
    input_ratio: 1.
