parent_cfg: configs/exps/pretrain/enerf/dtu_pretrain.yaml
gpus: [0]
exp_name: mvsnerf

# module
network_module: lib.networks.boost_mvsnerf.network

# task config
enerf:
    train_input_views: [5, 6, 7]
    test_input_views: 6
    cost_volume_input_views: 3
    cas_config:
        k_best: 4